# Site 
name: "GranaData"
title: "GranaData"
description: "Data science from Granada to the world."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: https://granadata.art
baseurl: 
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://gmail.us4.list-manage.com/subscribe/post?u=6bc2f64e5d9109bd06bf859c5&amp;id=68bbfe755b&amp;f_id=005c05e9f0'
include: ["_pages"]
permalink: /:title/
mode: night
twitter_username: GranaDataJose

# Authors
authors:
  jose:
    name: Jose
    display_name: Jose    
    avatar: 'assets/images/JoseAvatar.png'
    email: joseperez2000@hotmail.es
    web: https://jerry-master.github.io/Home-Page/
    twitter: https://twitter.com/GranaDataJose
    description: "Data scientist from Alcalá la Real. Studied at BarcelonaTech, worked as a researcher at the UGR and UPC, was a machine learning engineer at El Ranchito and Nemeda and now work in Koh Young Research Spain. Always wanting to explain my knowledge to the world."


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll_inline_highlight

safe: false
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'highlight'
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
