version: "3"

services:
  web:
    build: .
    command: sh start.sh
    environment:
      - DB_PASSWORD
    volumes:
      - .:/code
    ports:
      - 80:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: jose
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U jose -d webapp
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 30s